FROM --platform=linux/amd64 ubuntu:22.04 as builder

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential imagemagick

COPY . /repo
WORKDIR /repo/src/main/cpp
RUN make -j8

RUN mkdir -p /deps
RUN ldd /repo/src/main/cpp/tiv | tr -s '[:blank:]' '\n' | grep '^/' | xargs -I % sh -c 'cp % /deps;'

FROM ubuntu:22.04 as package

COPY --from=builder /deps /deps
COPY --from=builder /repo/src/main/cpp/tiv /repo/src/main/cpp/tiv
ENV LD_LIBRARY_PATH=/deps
